### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by lucascomamala** [sajibarafatsiddiqui/rails-recipe-app#12]
https://github.com/sajibarafatsiddiqui/rails-recipe-app/projects/1

3 person team

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @sajibarafatsiddiqui, and Team👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [x] Most of the task cards are missing descriptions, Please make sure all task cards have descriptions.
![image](https://github.com/sajibarafatsiddiqui/rails-recipe-app/assets/83803414/45d301b5-9d41-43e0-927f-d440e185bee2).

- [x] Please make sure time estimate distributions should be fair(Points) among team members. (no single person should be doing all of the most time-consuming tasks). Currently, it's not fair.
- [x] Please make sure the task cards are created based on these [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md) bullet points. Currently, the Kanban board is missing some requirement task cards.
- [x] I can see you're three members for this project, but I can't see tasks assigned to the third member. Please make sure task cards have three members assigned to them fairly.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucascomamala** [comment]
Suggestions have been implemented, thanks!

**Comment by andersonlebon** [comment]
## Hi @team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
